# Generated by Django 3.0.8 on 2020-07-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='ifsc_code',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
